drop table if exists stats;

create table if not exists stats(
    stat_id     bigint generated by default as identity primary key,
    stat_app    varchar(255) not null,
    stat_uri    varchar(255) not null,
    stat_ip     varchar(255) not null,
    timestamp   timestamp not null
);